version: '2.4'

services:

  secrets:
    container_name: secrets
    image: vault:1.3.4
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    volumes: 
      - ./volumes/config:/vault/config
      - ./volumes/file:/vault/file
      - ./volumes/logs:/vault/logs
    entrypoint: vault server -config=/vault/config/vault.json

  rabbitmq:
    container_name: rmq
    # This variant includes the management UI.
    image: 'rabbitmq:3.6-management-alpine'
    ports:
      # The standard AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'

  edge_service:
    container_name: edge_service_v1
    build:
      context: ./edge_service
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      # - APP_NAME=edge_service
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=0
      # - APP_SETTINGS=project.server.config.ProductionConfig
      # - SECRET_KEY=change_me_in_prod
    depends_on:
      - user_service
      - rabbitmq
    cap_drop: 
      - MKNOD
      - CHOWN
      - NET_RAW
      - SETPCAP
      - AUDIT_WRITE
      - DAC_OVERRIDE
      - FOWNER
      - FSETID
      - KILL
      - SETGID
      - SETUID
      - NET_BIND_SERVICE
      - SYS_CHROOT
      - SETFCAP


  user_service:
    container_name: user_service_v1
    build:
      context: ./user_service
      dockerfile: Dockerfile
    environment:
      # - APP_NAME=user_service
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=0
      # - APP_SETTINGS=project.server.config.ProductionConfig
      # - DATABASE_URL=postgres://postgres:postgres@user_service_db:5432/users_dev
      # - DATABASE_TEST_URL=postgres://postgres:postgres@user_service_db:5432/users_test
      # - SECRET_KEY=change_me_in_prod
    depends_on:
      - user_service_db
      - rabbitmq
    cap_drop: 
      - MKNOD
      - CHOWN
      - NET_RAW
      - SETPCAP
      - AUDIT_WRITE
      - DAC_OVERRIDE
      - FOWNER
      - FSETID
      - KILL
      - SETGID
      - SETUID
      - NET_BIND_SERVICE
      - SYS_CHROOT
      - SETFCAP


  user_service_db:
    container_name: user_service_v1_db
    build:
      context: ./user_service/db
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

